-- Migration 002: Project Documents section
--
-- Adds two ways to see a project's documents clearly in pgAdmin:
--
-- 1. project_documents_view
--    A VIEW (shows up in pgAdmin under Databases > up_rera >
--    Schemas > public > Views) with one row PER DOCUMENT,
--    joined with its project's registration_number and
--    project_name. Columns document_name and document_url sit
--    side by side, and every document for a project appears as
--    its own row underneath that project when you sort/filter
--    by registration_number. This is the recommended way to
--    browse documents per project in pgAdmin - open it like a
--    table via View/Edit Data > All Rows.
--
-- 2. projects.documents_summary
--    A plain TEXT column added directly to the projects table,
--    so you can see all of a project's documents at a glance
--    without leaving that table. Each document appears on its
--    own line as "Document Name -> URL". This is generated by
--    the loader (db/loader.py) alongside documents_json.
--
-- Safe to run multiple times.

ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS documents_summary TEXT;

COMMENT ON COLUMN projects.documents_summary IS
    'Human-readable "Document Name -> URL" list, one document per line, for quick viewing in pgAdmin.';

CREATE OR REPLACE VIEW project_documents_view AS
SELECT
    pr.id                    AS project_id,
    pr.registration_number,
    pr.project_name,
    pd.serial_number,
    pd.document_name,
    pd.file_name,
    pd.document_type,
    pd.uploaded_date,
    pd.document_url
FROM projects pr
JOIN project_documents pd ON pd.project_id = pr.id
ORDER BY pr.registration_number, pd.serial_number;

COMMENT ON VIEW project_documents_view IS
    'One row per document, joined with its project. Browse this in pgAdmin (Views) to see document_name and document_url per project without writing a join yourself.';
